### ISSUE TITLE
Structure, Sequence, and Organization - Licenses

### ISSUE THREAD

**Issue by kardianos** [didip/tollbooth#1]
It isn't typical to prefix packages with "lib" in "libstring". Of note, go packages tend to be much larger than Java classes. All the sub packages you wrote would probably be better in the primary package.

Your vendoring of a juju rate limit is fine, but the license mixture may not be. You need to either write your own rate limit package or note that part of your package uses a LGPLv3 with exception. The license you have brought in needs to be called out.

**Comment by didip** [comment]
Oh, good point on the LGPLv3 license. I will reach out to the author and figure this out.

**Comment by didip** [comment]
Looks like outside projects linking to `github.com/juju/ratelimit` is covered under *Combined Work*. 
Specifically, permission to link library is defined [here](https://github.com/juju/ratelimit/blob/master/LICENSE#L9).
