### ISSUE TITLE
Question: How to Limit Max Number of Requests Per Hour

### ISSUE THREAD

**Issue by FloatingSunfish** [didip/tollbooth#102]
I'm new to rate limiting and want to use `tollbooth` to limit HTTP requests.

I also read the ***[Token Bucket Algorithm][1]*** page on Wikipedia.

For a simple test app, I want to limit the max number of concurrent requests to `10` *regardless* of request IP, and have a max burst size of `3` *based* on request IP.

***NOTE:*** The `10` and `3` are just to make rate limiting easier to observe.

Below is my code based on the examples on `tollbooth`'s ***[GitHub page][2]***:

    package main
    
    import (
        "net/http"
        "time"
    
        "github.com/didip/tollbooth/v7"
        "github.com/didip/tollbooth/v7/limiter"
    )
    
    func main() {
        lmt := tollbooth.NewLimiter(3, &limiter.ExpirableOptions{DefaultExpirationTTL: time.Hour})
    
        http.Handle("/", tollbooth.LimitFuncHandler(lmt, HelloHandler))
        http.ListenAndServe(":8080", nil)
    }
    
    func HelloHandler(w http.ResponseWriter, req *http.Request) {
        w.Write([]byte("Hello, World!"))
    }

I test the code by running `curl -i localhost:8080` several times in rapid succession, and I do get `HTTP/1.1 429 Too Many Requests` errors whenever I exceed the rate limit I set.

Below are my questions:

1. How do I use `tollbooth` to limit max number of concurrent requests to something like `10`?
   And does it even make sense to do so? I assume it does because rate limiting based only on IPs sounds like the server could still go out of memory when too many IPs access it at once.

2. Am I approaching rate limiting correctly, or am I missing something? Perhaps this is something that's better handled by whatever load balancer is working with the app in the cloud?

  [1]: https://en.wikipedia.org/wiki/Token_bucket
  [2]: https://github.com/didip/tollbooth

**Comment by FloatingSunfish** [comment]
I got a great answer [here](https://stackoverflow.com/questions/73439068/limit-max-number-of-requests-per-hour-with-didip-tollbooth).

**Comment by pdxrlj** [comment]
What does this mean DefaultExpirationTTL? I read the comments of the code, but I can't understand it. I also wrote some test code, the result seems to have nothing to do with it. Can you tell me how you tested this
