### ISSUE TITLE
Can this be used as a go-restful filter

### ISSUE THREAD

**Issue by kitwalker12** [didip/tollbooth#11]
Planning to use it with [go-restful](https://github.com/emicklei/go-restful)
Go-restful has Filters that can be attached to request handlers like [this](https://github.com/emicklei/go-restful/blob/master/examples/restful-basic-authentication.go)

I was wondering if a true/false value could be returned using the limiter struct

**Comment by didip** [comment]
Sorry for the belated reply, somehow I didn't get a message on this PR.
Thank you for the contribution!
