### ISSUE TITLE
bug or feature?

### ISSUE THREAD

**Issue by xwb1989** [didip/tollbooth#13]
Here:

https://github.com/didip/tollbooth/blob/master/config/config_test.go#L32

Is this "off by 1" a bug not fixed yet or an intentional "feature"?

**Comment by didip** [comment]
That logic is actually handled by `github.com/juju/ratelimit` library. See: https://github.com/juju/ratelimit/blob/master/ratelimit.go#L205

I haven't been able to spend more time digging through it, unfortunately.
