### ISSUE TITLE
Set response headers "X-Rate-Limit-*"

### ISSUE THREAD

**Issue by cd1** [didip/tollbooth#15]
There are some response headers which are useful to indicate the current context of rate limiting, for example:

```
X-Rate-Limit-Limit: 30
X-Rate-Limit-Remaining: 11
X-Rate-Limit-Reset: 44
```

More details here: https://www.fullcontact.com/developer/docs/rate-limits/

It would be nice to have those headers set by tollbooth as well.

**Comment by didip** [comment]
@cd1 I've added

```
X-Rate-Limit-Limit
X-Rate-Limit-Duration
```

but unfortunately, `X-Rate-Limit-Remaining` and `X-Rate-Limit-Reset` is not possible because `juju/ratelimit` does not expose those as public variables.
