### ISSUE TITLE
Only 1 token returned after duration

### ISSUE THREAD

**Issue by VadimBelov** [didip/tollbooth#17]
In scenario of 30 permitted requests per second I'm using "tollbooth.NewLimiter(30, time.Second)".

Reproduction steps:
1. Send 50 requests during 1 second 
2. 30 requests are processed, 20 are thrown away because of (configured) throttling - correct
3. After 1 second send another 30 requests
4. Only 1 request is processed, 29 are thrown away, instead of being processed
You may repeat steps 3 and 4 and see the same unwanted result

My solution is to replace:
l.tokenBuckets[key] = ratelimit.NewBucket(l.TTL, l.Max)
with:
l.tokenBuckets[key] = ratelimit.NewBucketWithQuantum(l.TTL, l.Max, l.Max)

NewBucket "fills at the rate of one token every fillInterval", and it's expected that every fillInterval we would get the full bucket again. NewBucketWithQuantum solves this exactly with quantum parameter. 

After testing - after the same 1 configured second we get all the quota available again and further requests are not thrown away (in step 4).

**Comment by didip** [comment]
Merged
