### ISSUE TITLE
Rate limiting by IP can be defeated using headers

### ISSUE THREAD

**Issue by mjq** [didip/tollbooth#2]
It looks like this library always uses the IP given in the `X-Real-IP` or `X-Forwarded-For` request headers if provided. Unless the Go server is behind e.g. a load balancer that scrubs these headers, a user can mask their own IP (and potentially get around rate limits) just by changing these headers.

Library users should be able to specify whether they trust those header values (because they know it's safe to do so), or whether the actual requesting IP should be used instead.

**Comment by didip** [comment]
Ah, good point! spoofing is bad.
