### ISSUE TITLE
can this library be used in production?

### ISSUE THREAD

**Issue by sanathp** [didip/tollbooth#20]
can this library be used in production?
Have you done any benchmark testing ? 
is there any limit how many requests per second this can handle without causing much latency ?

**Comment by didip** [comment]
Yes, I have used this library on two services in prod.

The breaking points of this library is benchmarked here: https://github.com/didip/tollbooth/blob/master/tollbooth_benchmark_test.go. You can run it on your own hardware to have a better feel.

The actual rate limit logic is handled by an external library: github.com/juju/ratelimit. That library is used by Ubuntu's Juju project. Which is a fairly large production app.

I hope this helps.

**Comment by sanathp** [comment]
Thanks for the response
