### ISSUE TITLE
Limit x amount of requests in parallel

### ISSUE THREAD

**Issue by rogierlommers** [didip/tollbooth#28]
Can we use tollbooth to restrict the amount of accepted requests in parallel? The examples in the docs all make use of time (f.e. one req/sec), ipaddress, etc. Basically what I want is a way to handle my (mux) handlers only 2 at once.

**Comment by didip** [comment]
The library should have no problem handling parallel requests. You could achieve what you want by setting limit: 2/seconds or 2/milliseconds (depending on your traffic).
