### ISSUE TITLE
Using with Gin?

### ISSUE THREAD

**Issue by pyros2097** [didip/tollbooth#3]
Any ideas on how to use this as a middleware in [Gin](https://github.com/gin-gonic/gin)?
And can this used to prevent DDOS based on IP address?

**Comment by didip** [comment]
On IP address: Yes, by default the limiter limits by remote ip address and request's path.
On Gin Gonic: Give me some time to look at how it handles middleware.

**Comment by didip** [comment]
Gin middleware is now supported: https://github.com/didip/tollbooth/tree/master/third_party/tollbooth_gin

**Comment by josephzidell** [comment]
To update this, the new URL is: https://github.com/didip/tollbooth_gin
