### ISSUE TITLE
Cleanup tokenBuckets

### ISSUE THREAD

**Issue by janekolszak** [didip/tollbooth#30]
Hi,
I was just browsing the code and have one question:

Shouldn't tokenBuckets map in Limiter be cleaned up from old limiters from time to time?

**Comment by didip** [comment]
Great question. That is totally not handled at the moment.

Question for you, how can the middleware knows which limiters are old?

**Comment by janekolszak** [comment]
Maybe a configurable timeout?

**Comment by nicola-spb** [comment]
Will be memory leak?

**Comment by janekolszak** [comment]
Yes, it will leak.

**Comment by nicola-spb** [comment]
@janekolszak Thanks!

**Comment by didip** [comment]
User is now able to create an expire-able token buckets. See: https://github.com/didip/tollbooth/commit/7f43cd6b1c8e9b17da767ff14f391bb6499d63be
