### ISSUE TITLE
Memory usage of tollbooth in production

### ISSUE THREAD

**Issue by jack-chung** [didip/tollbooth#32]
Hi,

Is there any guidance on amount of memory needed to use tollboth in a public facing high traffic site?
Also, any guidance on applying tollbooth across all web nodes instead of per machine?

Thanks!

**Comment by jack-chung** [comment]
It doesn't look like config.tokenBuckets is ever cleaned up or am I missing something?

**Comment by didip** [comment]
Yes, this was a long standing bug. With this commit: https://github.com/didip/tollbooth/commit/7f43cd6b1c8e9b17da767ff14f391bb6499d63be, you are now able to create a limiter with expire-able token bucket.
