### ISSUE TITLE
Trigger function when rate limit is hit

### ISSUE THREAD

**Issue by gravis** [didip/tollbooth#33]
I would like to be able to log the IPs hitting the rate limit.
This could be easily done by adding a callback `func(r *http.Request)` in the limiter, and invoked  somewhere around:
https://github.com/didip/tollbooth/blob/master/tollbooth.go#L39

What do you think?

**Comment by didip** [comment]
Yeah, this sounds like a good idea. As you suggested, you can create a public field called OnLimitReached, and assigned that during limiter creation.

Would you like to send PR? :)

**Comment by didip** [comment]
I believe this PR satisfy this ticket needs: https://github.com/didip/tollbooth/pull/42
