### ISSUE TITLE
Limiting more than configured

### ISSUE THREAD

**Issue by frasergraham** [didip/tollbooth#36]
I'm wondering if i've configured tollbooth incorrectly because i'm seeing it limit my requests much more aggressively than I would like.

My limiter is simple...

    	s.globalLimiter = tollbooth.NewLimiter(rateLimitGlobal, time.Second)

where rateLimitGlobal is 300, and then as a wrapper around my HandleFunc...

	if err := tollbooth.LimitByRequest(s.globalLimiter, req); err != nil {
		compute.HandleError(w, fmt.Sprintf("server has exceeded rate limit (%d/s)", s.globalLimiter.Max), "", http.StatusTooManyRequests)
		return
	}
    

but when I test a basic route by hitting it with 10 calls per second serially, after the first few hundred requests it started returning 429 for 9/10 requests. Effectively limiting everything to 1/s which is way too slow.

Am I mis-understanding how this works? What am I doing wrong here?

**Comment by frasergraham** [comment]
On looking at the rate package directly, it seems these values are not what I expected and the first number is just the bucket size, and the second value is the only one that matters for limiting a continuous high load.

**Comment by SCKelemen** [comment]
@frasergraham  Is this issue resolved, and can we close it?
