### ISSUE TITLE
Ratelimit by user-identifier

### ISSUE THREAD

**Issue by richardartoul** [didip/tollbooth#43]
Hello!

First off, nice library :)

I'm looking through the code and wondering if tollbooth supports the use-case I'm looking for. All of my users have an API key which they pass in a header, and I want to ratelimit them by that key. However, I don't want to pre-fetch all possible API keys from my database and pre-populated the tollbooth limiter. I want the limiter to just ratelimit based on whatever API key is present without knowing what the values are beforehand.

Is that possible with the existing interface?

**Comment by rvdwijngaard** [comment]
this is exactly what I need

**Comment by didip** [comment]
The tricky part about this feature is that middleware is loaded once on-boot when HTTP routes are defined the 1st time.

To support this, the library needs to provide a channel for updating `Headers` in a thread-safe way. It's doable, but it will require refactoring quite a bit. And once `Headers` behaves this way, other attributes will have to behave this way as well (for consistency).

Unfortunately, I am currently very busy with work so it's hard to set aside time to work on this. I hope you understand.

**Comment by didip** [comment]
`v2.0.0` is now able to support your use-case.

All of Tollbooth variables are now thread-safe. You can do this every time your app sees a new api token:

```
// 1. Create a limiter and pass it around your app wherever you need
lmt := tollbooth.NewLimiter(10, time.Second, nil)

// 2. Add header entries as you keep seeing new API tokens.
lmt.AddHeaderEntries("X-API-TOKEN", []string{"jon-snow-key", "sansa-key"})

// 3. And if you don't want to rate-limit a certain user
lmt.RemoveHeaderEntries("X-API-TOKEN", []string{"jon-snow-key"})
```

Note that I haven't come up with a clean way to automatically expires these header entries. It's up to you to automatically clean them.

Hope it helps.
