### ISSUE TITLE
SemVem releases

### ISSUE THREAD

**Issue by rv-rsouza** [didip/tollbooth#44]
Please, consider tagging your releases using (SemVer)[http://semver.org].

All dependency/package managers use the version number to "lock" dependencies.

This will be a great improvement.

`git tag v1.0.0 -m "first release" && git push --follow-tags`

Thanks!

**Comment by didip** [comment]
Done. See: https://github.com/didip/tollbooth/tree/v1.0.0

**Comment by rv-rsouza** [comment]
Thank you very much!
