### ISSUE TITLE
Get IP address in Reject Function

### ISSUE THREAD

**Issue by chaehni** [didip/tollbooth#45]
Is it possible to get the IP address of the blocked request in the reject function for logging?

**Comment by didip** [comment]
I think the blocked IP could be easily added to HTTP response header.

**Comment by didip** [comment]
The rejected request IP addresses are now recorded in response HTTP header.

See: `X-Rate-Limit-Request-Forwarded-For` and `X-Rate-Limit-Request-Remote-Addr`
