### ISSUE TITLE
Additional headers

### ISSUE THREAD

**Issue by josephzidell** [didip/tollbooth#46]
Hey!

Would it be possible to have access to data for additional headers:

- `X-Rate-Limit-Remaining` The number of remaining requests in the current period
- `X-Rate-Limit-Reset` The number of seconds left in the current period

This will help my users

**Comment by josephzidell** [comment]
OpenAPI reference: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#headers-object-example

**Comment by didip** [comment]
Yes, I really wish that Tollbooth can support this. But unfortunately, the low level rate limiter: https://godoc.org/golang.org/x/time/rate could not give everything we want.
