### ISSUE TITLE
Limiter doesn't behave as documentation describes

### ISSUE THREAD

**Issue by tylerb** [didip/tollbooth#48]
Greetings!

I am seeing some odd behavior with how the limiter limits requests.

We are constructing a limiter like this:

```go
limiter := tollbooth.NewLimiter(20, time.Second, nil)
```

My understanding of this, based on the documentation and code, is that the limiter will now allow a maximum of 20 requests per second, per path, per IP. If a client attempts to exceed 20 req/sec/path/IP, it will receive a 429 response.

However, this is not what we are seeing. We have a client that hits the same path about 2 times per second. After about six minutes at 2 req/sec, tollbooth starts responding with 429 errors here and there.

Either my understanding of how it is supposed to work is incorrect, or my configuration is incorrect, but it seems that setting 20/time.Second should *never* cause a 429 response under a load of 2/req/sec/path/IP.

Is it possible there is a bug somewhere in this package?

Please let me know what I'm missing here. Thanks!

**Comment by didip** [comment]
Your expectation is correct, there has to be a bug here. Let me take a look.

**Comment by tylerb** [comment]
Excellent. Thank you! Please let me know if I can be of assistance.

**Comment by didip** [comment]
@tylerb Can I see an example on how you use it on your HTTP router?

**Comment by didip** [comment]
I have written a test case for what I think describes your problem, but the test is passing.

Can you check if it correctly represents your problem? https://github.com/didip/tollbooth/blob/master/tollbooth_bug_report_test.go

**Comment by tylerb** [comment]
@didip thanks for that. It does not correctly represent my problem. I will take your test case and see if I can make it fail in the way I am seeing. Thanks for writing it!

**Comment by tylerb** [comment]
@didip I've managed to write a test case that reliably reproduces my issue.

```
--- FAIL: Test_Issue48_RequestTerminatedEvenOnLowVolumeOnSameIP (20.14s)
	tollbooth_bug_report_test.go:47: Should be able to handle 20 reqs/second. HTTP status: 429. Expected HTTP status: 200. Failed after 39 iterations in 20.138660 seconds.
```

Here's the code:

``` go
// See: https://github.com/didip/tollbooth/issues/48
func Test_Issue48_RequestTerminatedEvenOnLowVolumeOnSameIP(t *testing.T) {
	lmt := limiter.New(nil).SetMax(20).SetTTL(time.Second)
	lmt.SetMethods([]string{"GET"})

	limitReachedCounter := 0
	lmt.SetOnLimitReached(func(w http.ResponseWriter, r *http.Request) { limitReachedCounter++ })

	handler := LimitHandler(lmt, http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte(`hello world`))
	}))

	// The issue seen by the reporter is that the limiter slowly "leaks", causing requests
	// to fail after a prolonged period of continuous usage. Try to model that here.
	//
	// Report stated that a constant 2 requests per second over several minutes would cause
	// a limit of 20/req/sec to start returning 429.
	timeout := time.After(10 * time.Minute)
	iterations := 0
	start := time.Now()
	for {
		select {
		case <-timeout:
			break
		case <-time.After(500 * time.Millisecond):
			req, _ := http.NewRequest("GET", "/doesntmatter", nil)
			req.RemoteAddr = "127.0.0.1"

			rr := httptest.NewRecorder()
			handler.ServeHTTP(rr, req)

			if status := rr.Code; status != http.StatusOK {
				t.Fatalf("Should be able to handle 20 reqs/second. HTTP status: %v. Expected HTTP status: %v. Failed after %d iterations in %f seconds.", status, http.StatusOK, iterations, time.Since(start).Seconds())
			}
			iterations++
		}
	}

	if limitReachedCounter > 0 {
		t.Fatalf("We should never reached the limit, the counter should be 0. limitReachedCounter: %v", limitReachedCounter)
	}
}
```

**Comment by didip** [comment]
Looks like https://godoc.org/golang.org/x/time/rate#Limiter.AllowN suddenly return false. I don't know what cause it to behave like that yet. See: https://github.com/didip/tollbooth/blob/master/limiter/limiter.go#L462

**Comment by tylerb** [comment]
I think you may be using the token bucket incorrectly.

According to my reading of the documentation, the bucket refills at a rate of `r` tokens per second, which is the first argument to the constructor. The second argument is the max burst size.

It appears you are passing the TTL (1 in my case) to the `r` argument, meaning the bucket is only being refilled at 1 token per second.

I believe if you pass the max as the first argument, this issue will be fixed.

It also appears that the token bucket ALWAYS operates at `r` tokens per second and you cannot tell it to refill on a different delay. I think this means you will either need to change your interface, or do some math before initializing the token bucket.

For example you could do `max/ttl` to get the `r` argument. I think it might be better to remove TTL altogether and only allow a “per second” number like the bucket expects.

**Comment by didip** [comment]
Oh wow, you are indeed correct. Thank you for catching this!
