### ISSUE TITLE
about get real ip from http.Request

### ISSUE THREAD

**Issue by conc** [didip/tollbooth#5]
如果用户自己在http header中添加"X-Real-IP"，这里获取到的ip也就不是真的ip了，这样对ip的限制会不会有问题了。
我自己也遇到了这样的问题，因此在这里提出来问一下。

**Comment by xyproto** [comment]
Poor translation, with Google Translate:

> If the user to add their own "X-Real-IP" in the http header in here to get to the ip ip so it is not true, so restrictions on ip will not be a problem. I also encountered such a problem, so raised here ask.

**Comment by didip** [comment]
@conc I'll do my best to guess :)
I think you are asking if user defines `X-Real-IP`, is it going to be a problem?

It won't be, just defined the order on how you want to look up IP. Example:
```
limiter := tollbooth.NewLimiter(1, time.Second)

// Configure list of places to look for IP address.
// By default it's: "RemoteAddr", "X-Forwarded-For", "X-Real-IP"
// If your application is behind a proxy, set "X-Real-IP" or "X-Forwarded-For" first.
limiter.IPLookups = []string{"X-Real-IP", "X-Forwarded-For", "RemoteAddr"}
```

**Comment by conc** [comment]
@didip oh，thanks。I will have a try.
@xyproto sory,my english is poor,so I use chinese instead.It seems that Google Translate is very exact。
