### ISSUE TITLE
Changing rate limit based on minute or hour.

### ISSUE THREAD

**Issue by rebootcode** [didip/tollbooth#54]
After reading these 2 issues #48 and #51 , I could not understand, how can someone limit the request based on minute or hour.

Is there any hack available, where I can set  **10 requests per minute** and **not 10 requests per second**

Current support is only for second, but to me second does not makes sense.

**Comment by didip** [comment]
Just multiply it by 60 to get per minute limit.

**Comment by rebootcode** [comment]
What do you multiply? Can you please share code. Is this how you do , 

```
package main

import (
    "github.com/didip/tollbooth"
    "net/http"
    "time"
)

func HelloHandler(w http.ResponseWriter, req *http.Request) {
    w.Write([]byte("Hello, World!"))
}

func main() {
    // Create a request limiter per handler.
    http.Handle("/", tollbooth.LimitFuncHandler(tollbooth.NewLimiter(60, nil), HelloHandler))
    http.ListenAndServe(":12345", nil)
}
```

but doesn't that mean - **60 request per seond** and not **1 request per minute**

**Comment by davis12529** [comment]
@rebootcode Since `max` argument for `tollbooth.NewLimiter` is int64, the lowest you can go is **1 request per second** i.e. **60 request per minute**, as discussed [here](https://github.com/didip/tollbooth/pull/52#issuecomment-343015102). If you urgently need to set lower than **60 request per minute**, you have to fork it and modify the `max` argument to your needs.

**Comment by didip** [comment]
@rebootcode I see what you want to do... @davis12529  is correct, we are limited to what https://godoc.org/golang.org/x/time/rate can do, and it limits on per second basis.

**Comment by anopheles** [comment]
The limit seems to have changed to a float in https://godoc.org/golang.org/x/time/rate is it possible to update your library to allow floats?
