### ISSUE TITLE
Allow floats for the maximum instead of ints

### ISSUE THREAD

**Issue by turt2live** [didip/tollbooth#58]
Currently tollbooth only accepts int64 as the maximum requests per second. Having this be a float instead would allow for more fractional limits, such as 0.2 requests per second (1 request every 5 seconds).

This should be relatively easy considering https://godoc.org/golang.org/x/time/rate#Limit supports floats

**Comment by rebootcode** [comment]
+1

**Comment by anopheles** [comment]
@didip 
I just added floating point support.
https://github.com/anopheles/tollbooth/commit/09484c62c2b75386a1448ef48a6fa1048b1cd09f

**Comment by didip** [comment]
@anopheles The fork looks good, wanna send PR? :)

**Comment by didip** [comment]
v4.0.0 is released to support this. Thanks for the PR!
