### ISSUE TITLE
how can i use tollboth in a distributed server environment?

### ISSUE THREAD

**Issue by llonchj** [didip/tollbooth#61]
I have several http servers and i want to share access information. how can i do it?
Thanks

**Comment by didip** [comment]
@llonchj Sorry for the late reply, somehow GitHub didn't notify me.

What kind of information do you want to share? Tollbooth is stateless by design so that users don't have to use any databases.

**Comment by marcsantiago** [comment]
@llonchj It wouldn't be so bad to write an interface around

github.com/patrickmn/go-cache

so that Memcache and or Redis is used instead

**Comment by weiwangchao** [comment]
题主没明白意思，应该是问是否支持redis做分布式整体限流吧？
