### ISSUE TITLE
Unable to limit the request

### ISSUE THREAD

**Issue by raazcrzy** [didip/tollbooth#65]
I am trying out tollbooth to use in my project, but am not able to get the desired behavior.  Below is the middleware I am using. When I set `SetBurst()` to any positive number it never limits the requests, though when I try by setting it to `0` all requests gets blocked. Is there something I am missing out on?
```
func (rL *RateLimiter) ServeHTTP(response http.ResponseWriter, request *http.Request, next http.HandlerFunc) {
	lmt := limiter.New(&limiter.ExpirableOptions{DefaultExpirationTTL: time.Minute}).SetMax(2.0).SetBurst(1)
	lmt.SetMethods([]string{"GET", "POST"})
	httpError := tollbooth.LimitByRequest(lmt, response, request)
	if httpError != nil {
		response.Header().Add("Content-Type", lmt.GetMessageContentType())
		response.WriteHeader(httpError.StatusCode)
		response.Write([]byte(httpError.Message))
	} else {
		next(response, request)
	}
}
```

**Comment by brentmn** [comment]
Hi @raazcrzy,

The code in your example is initializing a new rate limiter with each request. Instead, `lmt` should be initialized and assigned to `rL` when you create `*RateLimiter`. Then:
```go
httpError := tollbooth.LimitByRequest(rL.lmt, response, request)
```

**Comment by raazcrzy** [comment]
@brentmn thanks for pointing out this silly mistake. Somehow I overlooked it. :+1:
