### ISSUE TITLE
Dynamically assigning rate-limits

### ISSUE THREAD

**Issue by octate** [didip/tollbooth#68]
Hi, I need some clarification on the following things:
 - Is it possible to create dynamic rate limits?
    eg: I would like to change the rate limit while the server is running.
 - Can I have different rate limits for different users?
   eg: I need to have different rate limits per username(basic-auth).

**Comment by didip** [comment]
1. Unfortunately not, it is not possible to dynamically change rate limit on the fly.
2. I think you can, just nest 2 tollbooth middlewares, one for user A and the other one for user B.
