### ISSUE TITLE
question:Can limiter discard the path dimension?

### ISSUE THREAD

**Issue by pantianying** [didip/tollbooth#80]
Can we cancel the flow calculation of URL dimension and replace it with a key? In my tests, the default limit count is isolated for each path, but some restful separated urls, such as / user / locate /{userid}/ login, have different paths per request. I need to customize the key to limit the current for such requests, so what should I do?

Looking forward to reply！

**Comment by didip** [comment]
You unfortunately have to create your own rate-limiting key.
