### ISSUE TITLE
SetOnLimitReached function doesn't seem to execute

### ISSUE THREAD

**Issue by TheCodeN00b** [didip/tollbooth#81]
Hi. I have to say that I am a real beginner on Go, so this may definitely be my fault, but I can't get the `SetOnLimitReached` function to get called. I'm using `tollbooth_httprouter` and this is the code I'm using:

```
limiter := tollbooth.NewLimiter(1, nil)
limiter.SetOnLimitReached(func(w http.ResponseWriter, r *http.Request){		 
    ToCallWhenLimitReached(w,r,nil)
})

router.GET("/whatever", tollbooth_httprouter.LimitHandler(ToCall, limiter))
```

Thanks in advance.

**Comment by didip** [comment]
Unable to reproduce because `tollbooth_bug_report_test.go` uses `SetOnLimitReached`. https://github.com/didip/tollbooth/blob/master/tollbooth_bug_report_test.go#L26
