### ISSUE TITLE
How can I set 5 limit in 1 minute?

### ISSUE THREAD

**Issue by yakuter** [didip/tollbooth#83]
Hello, thank you for great plugin. I couldn't figure out how to set max allowed attempts is 5 in 1 minute?

**Comment by didip** [comment]
The rate limiter is strictly per second basis, so you can multiply by 60: `5* 60`

**Comment by jacohend** [comment]
@didip I don't understand- wouldn't that mean 5 * 60 per second, then? Don't we need to divide instead?

**Comment by tobias-kuendig** [comment]
For anyone wondering:

```go
tollbooth.NewLimiter(5 / 60, nil) // 5 requests per minute
```

works like a charm :ok_hand:

**Comment by abanoub-fathy** [comment]
you can write a middleware function that will help you to limit any number of requests in any time window

```go
func ApplyRateLimiter(maxRequests int64, period time.Duration, next http.HandlerFunc) http.Handler {
	rate := float64(maxRequests) / float64(period.Seconds())
	limiter := tollbooth.NewLimiter(rate, nil)
	return tollbooth.LimitFuncHandler(limiter, next)
}
```

**Comment by abanoub-fathy** [comment]
> @didip I don't understand- wouldn't that mean 5 * 60 per second, then? Don't we need to divide instead?

yes you are right
