### ISSUE TITLE
go-cache used for limiter leaking goroutines

### ISSUE THREAD

**Issue by paskal** [didip/tollbooth#84]
Hi @didip, thanks for your amazing work!

Using [goleak](https://github.com/uber-go/goleak) in [remark42](https://github.com/umputun/remark42) repo I found that we have tons of leaking goroutines in tests from the go-cache package. I've replaced it with internal implementation in [go-pkgz/lcw](https://github.com/go-pkgz/lcw) and switched remark42 to it only to discover that some other dependency of it utilizes `limiter` from this package, which in turn use go-cache.

This is how go-cache suppose to kill its goroutine: https://github.com/patrickmn/go-cache/blob/master/cache.go#L1123
It utilizes [runtime.SetFinalizer](https://golang.org/pkg/runtime/#SetFinalizer) which would work (as I understood it) only if we'll remove pointers to created instance of go-cache and then would wait for it to be collected by Garbage Collector.

This doesn't work well with tests and I don't know how well it works in "normal" flows. So, here is my question: would you accept a PR with a switch to some other expirable cache which doesn't rely on spawning goroutines, this way minimizing the footprint of the limiter?

**Comment by didip** [comment]
I definitely will accept PRs. It does sound like go-cache is problematic.

**Comment by paskal** [comment]
[bluele/gcache](https://github.com/bluele/gcache) is a good candidate but it requires specifying a size which is not a thing currently and we would expect it to be unlimited.

I'm trying to find other cache implementation which would have an unlimited size and not rely on goroutines, but I don't know if these two requirements can be satisfied at once.

Exposing `Close` method from limiter feels like an overkill as well. I'll continue digging.
