### ISSUE TITLE
Configurable option for using ratelimit standardization proposal

### ISSUE THREAD

**Issue by ioggstream** [didip/tollbooth#88]
## I wish

to be able to support via configuration the following standardization proposal: https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-ratelimit-headers

gh repo: https://github.com/ietf-wg-httpapi/ratelimit-headers

This is currently implemented by envoy-proxy, kong and 3scale.

## The spec

defines 3 ratelimit-headers, returning the current quota, remaining quota and delta-seconds before quota expires.

```
   RateLimit-Limit: 100
   RateLimit-Remaining: 50
   RateLimit-Reset: 60

```

**Comment by paskal** [comment]
@didip what do you think? If you want to have it, let me know and I'll work on the MR.

**Comment by didip** [comment]
@paskal Yeah, that would be great. However, last I checked the rate limiter library that we use does not expose these numbers.

**Comment by paskal** [comment]
We need to go deeper then:) I'll investigate that, it might turn out that it's impossible with the current set of APIs.

**Comment by Enrico204** [comment]
`setResponseHeaders` apparently returns some of these values (as headers):

* `X-Rate-Limit-Limit` which can be mapped 1:1 to `RateLimit-Limit` , the corresponding value is from `Limiter.GetMax()`
* `X-Rate-Limit-Duration` is currently hard-coded to `1`, this can be mapped to the optional `quota-policy` part of `RateLimit-Limit` value
* The `RateLimit-Reset` might be hard-coded to `1` for now (see above)

The only issue is `RateLimit-Remaining` (i.e. the number of requests left before the limiter kicks in). I dug into the code, and the value is currently stored privately inside the `rate.Limiter` from `golang.org/x/time/rate`, so it's a no-go.

I was thinking that the counter can be implemented internally in the library, however this means that some of the `golang.org/x/time/rate` code should be re-coded here.

**Comment by paskal** [comment]
The problem I saw when I started working on implementation is in LimitByRequest: code checks limits by multiple keys:

https://github.com/didip/tollbooth/blob/81303df34291efeac254b8aa89db677fb03309de/tollbooth.go#L283-L288

I think I'll go with counting the leftover limit for each of the keys and returning the lowest limit among all, which would be the source of truth for knowing how many requests you have left before you'll receive an error. It would require changing `LimitByKeys` signature, I'll create a separate function which will return not only httpError but also current limit.

Please let me know if embedding `time/rate` or the way I want to calculate the limit is wrong or could be improved.

**Comment by ioggstream** [comment]
@paskal me ad @unleashed Will have a look at the implementation and provide feedback on managing multiple keys.

**Comment by paskal** [comment]
@ioggstream, please let me know once you will look into it, I'll proceed then.

**Comment by ioggstream** [comment]
@paskal mention tollbooth in https://github.com/ietf-wg-httpapi/ratelimit-headers/issues/25
