### ISSUE TITLE
SetMethod is not working.

### ISSUE THREAD

**Issue by jasonkwh** [didip/tollbooth#91]
Hello there. I followed the guide and do the following:

lmt.SetMethods([]string{"POST"})

But it is not working. The limiter is still limiting the GET and all different kind of requests.

**Comment by jasonkwh** [comment]
I used tollbooth for my production project and right now it is causing serious problem..

More codes:

func main() {
	lmt := tollbooth.NewLimiter(1, nil)
	lmt.SetMethods([]string{"POST"}).
		SetMessageContentType("application/json; charset=utf-8").
		SetMessage(api.ErrorMessage("You have reached maximum request limit."))
	http.Handle("/", tollbooth.LimitFuncHandler(lmt, checkRequest))
	log.Fatal(http.ListenAndServeTLS(":443", "server.crt","server.key",nil))
}

GET still utilising the limiter...

**Comment by paskal** [comment]
Better later than never, I'll look into it if nobody minds.

**Comment by didip** [comment]
@paskal Thanks for chipping in, I definitely welcome it.

**Comment by didip** [comment]
I start working on the fix here: https://github.com/didip/tollbooth/tree/issue91

**Comment by paskal** [comment]
I have an unusually busy week, if you'll need help with something particular please let me know. Otherwise, I'll look into ratelimit headers issue by tomorrow.

**Comment by didip** [comment]
@paskal thank you for any of your contributions!
