### ISSUE TITLE
Tollbooth breaks Safari / iOS / iPad / etc.

### ISSUE THREAD

**Issue by Zamiell** [didip/tollbooth#92]
Both version 4 and the latest version of Tollbooth (version 6) write an empty string to the "X-Rate-Limit-Request-Forwarded-For" header:

-----------

<img src="https://cdn.discordapp.com/attachments/333680903748321282/786126582950395934/unknown.png">

-----------

Safari and iOS hate empty headers and will barf on them, causing any WebSocket connections to be immediately terminated. Thus, I believe that this is a bug in the library - it should never produce a null value for an HTTP header.

The relevant line in the library is here: https://github.com/didip/tollbooth/blob/master/tollbooth.go#L19

For reference, I am invoking Tollbooth with the following code (using the Gin HTTP framework, if that matters):

```go
limiter := tollbooth.NewLimiter(2, nil) // Limit each user to 2 requests per second
limiter.SetMessage(http.StatusText(http.StatusTooManyRequests))
limiterMiddleware := httpLimitHandler(limiter)
httpRouter.Use(limiterMiddleware)
```

Thanks for the library.

**Comment by Zamiell** [comment]
I suspect that the fix is something along the lines of:

```
w.Header().Add("X-Rate-Limit-Request-Forwarded-For", r.Header.Get("X-Forwarded-For"))
```
-->
```
xForwardedFor := r.Header.Get("X-Forwarded-For")
if strings.TrimSpace(xForwardedFor) != "" {
    w.Header().Add("X-Rate-Limit-Request-Forwarded-For", xForwardedFor)
}
```

**Comment by didip** [comment]
This sounds bad, we'll take a look at it.
